version: '3.9'
services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: podcast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  typesense:
    image: typesense/typesense:0.25.2
    environment:
      TYPESENSE_API_KEY: local-demo-key
    ports:
      - "8108:8108"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    image: python:3.12-slim
    command: sleep infinity
    depends_on:
      - db
      - typesense
      - redis
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/podcast
      TYPESENSE_API_KEY: local-demo-key
      REDIS_URL: redis://redis:6379/0
